/* 
  -- DO NOT EDIT THIS FILE
*/

import scansJson from '../../db/scans.json';
import { FindAllParams, Scan } from './types';

const scansData: Scan[] = scansJson.map(
  ({
    date,
    ...rest
  }: {
    id: string;
    date: string;
    cloudProviderId: string;
    scanSize: number;
    scanPrivateKey: string;
  }) => ({
    ...rest,
    date: new Date(date),
  })
);

export class ScanRepository {
  /**
   * Find all the scans
   * @param params
   * @param params.filterCallback filter all the scans that filterCallback returns true on them
   * @returns Scan[]
   */
  static findAll(params?: FindAllParams): Promise<Scan[]> {
    const filterCallback = params?.filterCallback;

    const filteredScans = !filterCallback
      ? scansData
      : scansData.filter(filterCallback);

    return new Promise((res) => {
      setTimeout(() => {
        res(filteredScans);
      }, filteredScans.length / 5);
    });
  }
}
