/* 
  -- DO NOT EDIT THIS FILE
*/

import cloudProvidersJson from '../../db/cloud-providers.json';
import { CloudProvider } from './types';

const cloudProvidersData: CloudProvider[] = cloudProvidersJson;

export class CloudProviderRepository {
  /**
   * Find all the cloud providers
   * @param params
   * @returns CloudProvider[]
   */
  static findAll(): Promise<CloudProvider[]> {
    return Promise.resolve(cloudProvidersData);
  }
}
